INSERT INTO CATEGORIA(NOMBRE, ACTIVO) VALUES ('Cremas', 1);
INSERT INTO CATEGORIA(NOMBRE, ACTIVO) VALUES ('Talcos', 1);
INSERT INTO CATEGORIA(NOMBRE, ACTIVO) VALUES ('Endulzantes', 1);
INSERT INTO CATEGORIA(NOMBRE, ACTIVO) VALUES ('Alimentos', 1);
go
