USE HEALTHFOOT
GO
USE HEALTHFOOT
GO
CREATE TABLE CATEGORIA
(
    ID         INT      NOT NULL IDENTITY,
    NOMBRE     NVARCHAR(50),
    ACTIVO     INT,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
)
GO
CREATE TABLE PRODUCTO
(
    ID           INT      NOT NULL IDENTITY,
    NOMBRE       NVARCHAR(100),
    CANTIDAD     INT,
    PRECIO       FLOAT,
    DESCRIPCION  TEXT,
    FK_CATEGORIA INT      NOT NULL,
    ACTIVO       INT,
    CREATED_AT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_CATEGORIA) REFERENCES CATEGORIA (ID)
)
GO

CREATE TABLE IMAGEN_PRODUCTO
(
    ID          INT NOT NULL IDENTITY,
    IMAGEN      NVARCHAR(255),
    FK_PRODUCTO INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_PRODUCTO) REFERENCES PRODUCTO (ID)
)
GO
CREATE TABLE CLIENTE
(
    ID               INT      NOT NULL IDENTITY,
    NOMBRE           NVARCHAR(50),
    APELLIDOS NVARCHAR(50),
    EMAIL NVARCHAR(255),
    ACTIVO           INT,
	ROL INT,
    CREATED_AT       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
)
GO

CREATE TABLE DIRECCION
(
    ID         INT      NOT NULL IDENTITY,
    ESTADO     NVARCHAR(50),
    CIUDAD     NVARCHAR(50),
    MUNICIPIO  NVARCHAR(50),
    COLONIA    NVARCHAR(100),
    CALLE      NVARCHAR(100),
    CP         NVARCHAR(8),
    NUMERO     NVARCHAR(10),
    ACTIVO     INT,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FK_CLIENTE INT NULL,
    PRIMARY KEY (ID),
	FOREIGN KEY (FK_CLIENTE) REFERENCES CLIENTE (ID)
)
GO


CREATE TABLE PROVEEDOR
(
    ID           INT      NOT NULL IDENTITY,
    NOMBRE       NVARCHAR(100),
    TELEFONO     NVARCHAR(15),
    CORREO       NVARCHAR(50),
    RFC          NVARCHAR(20),
    FK_DIRECCION INT      NOT NULL,
    ACTIVO       INT,
    CREATED_AT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_DIRECCION) REFERENCES DIRECCION (ID)
)
GO

CREATE TABLE ORDEN_PROVEEDOR
(
    ID           INT      NOT NULL IDENTITY,
    FK_PROVEEDOR INT      NOT NULL,
    FECHA        DATE,
    CREATED_AT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_PROVEEDOR) REFERENCES PROVEEDOR (ID)
)
GO
CREATE TABLE INSUMO
(
    ID            INT      NOT NULL IDENTITY,
    NOMBRE        NVARCHAR(100),
    CANTIDAD      INT,
    ACTIVO        INT,
    CREATED_AT    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
)
GO

CREATE TABLE INSUMO_ORDEN
(
    ID            INT      NOT NULL IDENTITY,
    CANTIDAD      INT,
    PRECIO        FLOAT,
    UNIDAD_MEDIDA NVARCHAR(50),
    ACTIVO        INT,
    CREATED_AT    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_ORDEN_PROVEEDOR INT NOT NULL,
    FK_INSUMO INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_ORDEN_PROVEEDOR) REFERENCES ORDEN_PROVEEDOR (ID),
    FOREIGN KEY (FK_INSUMO) REFERENCES INSUMO (ID)
)
GO

CREATE TABLE FORMULA
(
    ID          INT      NOT NULL IDENTITY,
    FK_PRODUCTO INT      NOT NULL,
    FK_INSUMO   INT      NOT NULL,
    UNIDAD_MEDIDA NVARCHAR(50),
    CANTIDAD    INT,
    CREATED_AT  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_PRODUCTO) REFERENCES PRODUCTO (ID),
    FOREIGN KEY (FK_INSUMO) REFERENCES INSUMO (ID)
)
GO



CREATE TABLE ORDEN
(
    ID         INT      NOT NULL IDENTITY,
    FECHA      DATE,
    FK_CLIENTE INT      NOT NULL,
	ESTATUS NVARCHAR(50),
    ACTIVO     INT,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_CLIENTE) REFERENCES CLIENTE (ID)
)
GO

CREATE TABLE DETALLE_ORDEN
(
    ID          INT NOT NULL IDENTITY,
    FK_ORDEN    INT NOT NULL,
    FK_PRODUCTO INT NOT NULL,
    CANTIDAD    INT,
    SUBTOTAL    FLOAT,
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_PRODUCTO) REFERENCES PRODUCTO (ID),
    FOREIGN KEY (FK_ORDEN) REFERENCES ORDEN (ID)
)
GO

CREATE TABLE VENTA
(
    ID           INT NOT NULL IDENTITY,
    FK_ORDEN     INT NOT NULL,
    FECHA        DATE,
    FK_DIRECCION INT NOT NULL,
	CREATED_AT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_ORDEN) REFERENCES ORDEN (ID),
    FOREIGN KEY (FK_DIRECCION) REFERENCES DIRECCION (ID)
)
GO

CREATE TABLE VEHICULO(
ID INT NOT NULL IDENTITY,
NOMBRE NVARCHAR(50),
MARCA NVARCHAR(50),
MODELO NVARCHAR(50),
CAPACIDAD NVARCHAR(50),
PESO NVARCHAR(50),
CILINDROS INT,
ACTIVO INT,
CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(ID))
GO

CREATE TABLE RUTA(
ID INT NOT NULL IDENTITY,
INICIO NVARCHAR(50),
FIN NVARCHAR(50),
DISTANCIA INT,
ACTIVO INT,
CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(ID))
GO

CREATE TABLE EMBARQUE(
ID INT NOT NULL IDENTITY,
ID_RUTA INT NOT NULL,
ID_VEHICULO INT NOT NULL,
FECHA DATE,
ACTIVO INT,
CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(ID),
FOREIGN KEY(ID_RUTA) REFERENCES RUTA(ID),
FOREIGN KEY(ID_VEHICULO) REFERENCES VEHICULO(ID),
)
GO

CREATE TABLE ENTREGA(
ID INT NOT NULL IDENTITY,
ID_VENTA INT NOT NULL,
ID_EMBARQUE INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(ID_EMBARQUE) REFERENCES EMBARQUE(ID),
FOREIGN KEY(ID_VENTA) REFERENCES(ID_VENTA)
)
GO

CREATE TABLE EMPLEADO(
     ID int  NOT NULL IDENTITY,
     EMAIL Nvarchar(100) unique,
     APELIDO_PATERNO Nvarchar(50),
     APELLIDO_MATERNO Nvarchar(50),
     ROL INT,
	 CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	 ACTIVO INT,
	 PRIMARY KEY(ID)
);
go

