//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.HealthFoot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_ORDEN
    {
        public int ID { get; set; }
        public int FK_ORDEN { get; set; }
        public int FK_PRODUCTO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<double> SUBTOTAL { get; set; }
    
        public virtual ORDEN ORDEN { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
