//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.HealthFoot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMULA
    {
        public int ID { get; set; }
        public int FK_PRODUCTO { get; set; }
        public int FK_INSUMO { get; set; }
        public string UNIDAD_MEDIDA { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    
        public virtual INSUMO INSUMO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
