//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.HealthFoot.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.Core.Objects;

    public partial class RUTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RUTA()
        {
            this.EMBARQUE = new HashSet<EMBARQUE>();
        }
    
        public int ID { get; set; }
        public string INICIO { get; set; }
        public string FIN { get; set; }
        public Nullable<int> DISTANCIA { get; set; }
        public Nullable<int> ACTIVO { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMBARQUE> EMBARQUE { get; set; }

        public void InsertaRuta()
        {
            using (var db = new HealthEntities())
            {
                var id = new ObjectParameter("IDR", typeof(int));
                db.spRUTAIn(id, this.INICIO, this.FIN, this.DISTANCIA);
            }
        }

        public void EditaRuta(int id)
        {
            using (var db = new HealthEntities())
            {
                db.spRUTAEd(id, this.INICIO, this.FIN, this.DISTANCIA);
            }
        }

        public void EliminaRuta(int id)
        {
            using (var db = new HealthEntities())
            {
                db.spRUTAEl(id);
            }
        }
    }
}
