//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.HealthFoot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public int ID { get; set; }
        public int FK_ORDEN { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public int FK_DIRECCION { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    
        public virtual DIRECCION DIRECCION { get; set; }
        public virtual ORDEN ORDEN { get; set; }
    }
}
